const hrMails = `
                        
shivanigautam@ducktaleit.com
hr.nectarbits@gmail.com
soniya@competentgroove.com
aanchal.tomar@xicom.biz
akanksha@opportunityhubb.com
rallanmamta@seasiainfotech.com
shwetas@impingeonline.com
mandeep@webspero.com
kamakshi.zigsaw@gmail.com
sudhanshu@cyberpuzzlenet.com
sakshidhanjal@devherds.com
preeti@rocked.us
itw.nishitad@gmail.com
kalpana@antiersolutions.com
aarushi.pundir@vinnisoft.org
hr.mohali@myvirtualteams.com
bmcloudc@gmail.com
khatripoonam69@gmail.com
bhavna.phulwani@nexuslink.in
ishita.codebrew@gmail.com
nandini.agrawal@octalsoftware.com
savita@spineor.com
ashmita.chhaparwal@angara.com
shivani@moontechnolabs.com
gurleen.kaur@weoinfotech.com
careers@shineinfosoft.in
shivani.singh@plaxonic.com
jasminerathee@zapbuild.com
shefhali@cwebconsultants.com
radhika.malhotra@ditstek.com
seerat@formics.io
careers@radicalloop.com
devi.modi@aipxperts.com
muskan.handa@recro.io
mehak.bansal@firminiq.com
manind@resourcesvalley.in
saryuthakur.ameotech@gmail.com
himanigupta@luminoguru.com
kajal.k@richestsoft.in
kalyani@unoiatech.com
sakshi@cronj.com
hrekrocx@gmail.com
krina.bundela@artoonsolutions.com
rimal.ghuman@ensuesoft.com
hr@tecxar.io
kesha.pandya@artoonsolutions.com
`
const AllMails = hrMails.trim().split('\n')
console.log(AllMails);